<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class SetupYouTubeCookies extends Command
{
    protected $signature = 'youtube:setup-cookies';

    protected $description = 'Setup YouTube cookies from base64-encoded ENV variable';

    public function handle(): int
    {
        $cookiesB64 = env('YOUTUBE_COOKIES_B64');
        $cookiesPath = config('sundo.youtube.cookies_path', storage_path('app/cookies.txt'));

        if (empty($cookiesB64)) {
            $this->info('YOUTUBE_COOKIES_B64 not set in environment, skipping cookies setup');

            return self::SUCCESS;
        }

        if (empty($cookiesPath)) {
            $this->error('Cookies path is empty. Please configure YOUTUBE_COOKIES_PATH or ensure config has a default.');

            return self::FAILURE;
        }

        $this->info('Setting up YouTube cookies...');
        $this->info('Cookies path: '.$cookiesPath);
        $this->info('Base64 length: '.strlen($cookiesB64).' bytes');

        // Create directory if it doesn't exist
        $directory = dirname($cookiesPath);
        if (empty($directory) || $directory === '.') {
            $directory = storage_path('app');
        }
        if (! File::exists($directory)) {
            File::makeDirectory($directory, 0755, true);
        }

        // Decode and write cookies file
        $decodedCookies = base64_decode($cookiesB64);

        if ($decodedCookies === false) {
            $this->error('Failed to decode base64 cookies');

            return self::FAILURE;
        }

        $netscapeHeader = "# Netscape HTTP Cookie File\n# This file is generated by Laravel. Do not edit.\n\n";
        $bytesWritten = File::put($cookiesPath, $netscapeHeader.$decodedCookies);

        if ($bytesWritten === false) {
            $this->error('Failed to write cookies file');

            return self::FAILURE;
        }

        // Set secure permissions
        chmod($cookiesPath, 0600);

        $this->info("YouTube cookies setup complete: {$cookiesPath}");
        $this->info('Cookies file size: '.$bytesWritten.' bytes');
        $this->info('Cookies line count: '.count(file($cookiesPath)).' entries');

        return self::SUCCESS;
    }
}
